/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 salsa-new.glb --transform 
Model Information:
* title:	santa claus dancing, modern santa, new year 2021
* source:	https://sketchfab.com/3d-models/santa-claus-dancing-modern-santa-new-year-2021-86a017a23f514dfeaa1e8259cddb349e
* author:	NataLya (https://sketchfab.com/martalernata)
*/

import React, { useRef, useEffect, useState } from 'react'
import { useAnimations, useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const DISTANCE_OFFSET = 45;

export function Salsa(props) {
  const group = useRef()
  const scroll = useScroll();
  const { nodes, materials, animations } = useGLTF("./models/salsa-new-transformed.glb")
  const { actions, names } = useAnimations(animations, group)
  const [initialPosition] = useState(props.position);
  console.log('actions',actions)
  console.log(names,'names')

  useFrame((state, delta) => {
    group.current.position.x =
      initialPosition[0] -
      (initialPosition[0] < 0 ? DISTANCE_OFFSET : -DISTANCE_OFFSET) *
        (1 - scroll.offset)+9;
    group.current.rotation.y = 2 * Math.PI * scroll.offset;
  });

  useEffect(() => {
    actions[names[props.animationIndex]].reset().fadeIn(0.5).play();
    
    return () => {
      actions[names[props.animationIndex]].fadeOut(0.5);
    };
  }, [props.animationIndex]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh  name="group_barbes" geometry={nodes.group_barbes.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_barbes.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh  name="group_boots" geometry={nodes.group_boots.geometry} material={materials.PaletteMaterial002} skeleton={nodes.group_boots.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_boots_semelle" geometry={nodes.group_boots_semelle.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_boots_semelle.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_Ceinturon" geometry={nodes.group_Ceinturon.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_Ceinturon.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_ceinturon_boucle" geometry={nodes.group_ceinturon_boucle.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_ceinturon_boucle.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_Default" geometry={nodes.group_Default.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_Default.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_eyes" geometry={nodes.group_eyes.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_eyes.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_eyes_little" geometry={nodes.group_eyes_little.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_eyes_little.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_main" geometry={nodes.group_main.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_main.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_man" geometry={nodes.group_man.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_man.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_ongles" geometry={nodes.group_ongles.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_ongles.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_pantalon" geometry={nodes.group_pantalon.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_pantalon.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="group_White" geometry={nodes.group_White.geometry} material={materials.PaletteMaterial001} skeleton={nodes.group_White.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload("./models/salsa-new-transformed.glb")
